### ISSUE TITLE
Need to fix notifications from this repo

### ISSUE THREAD

**Issue by MaxwellMorris** [Curtin-Machine-Learning-Club/Internal-Admin#11]
Need to make it so you don't get an email notifcation every time something happens.

**Comment by nanookmetaal** [comment]
![gh](https://user-images.githubusercontent.com/47708756/77085896-f12b8f80-6a3b-11ea-8444-afcf12738fa5.png)
just wondering are u subscribed to everything?

**Comment by MaxwellMorris** [comment]
I think I've found the solution on: https://help.github.com/en/github/receiving-notifications-about-activity-on-github/choosing-the-delivery-method-for-your-notifications .

I just didn't want to have to select unsubscribe for every single issue.
